// ICAO airline designators (3-letter callsign prefix) -> airline name
// Covers the ~150 most common airlines worldwide
const AIRLINES: Record<string, string> = {
  // North America
  AAL: "American Airlines",
  UAL: "United Airlines",
  DAL: "Delta Air Lines",
  SWA: "Southwest Airlines",
  JBU: "JetBlue Airways",
  NKS: "Spirit Airlines",
  FFT: "Frontier Airlines",
  ASA: "Alaska Airlines",
  HAL: "Hawaiian Airlines",
  ACA: "Air Canada",
  WJA: "WestJet",
  VOI: "Volaris",
  AMX: "Aeromexico",

  // Europe
  BAW: "British Airways",
  RYR: "Ryanair",
  EZY: "easyJet",
  EZS: "easyJet Switzerland",
  DLH: "Lufthansa",
  AFR: "Air France",
  KLM: "KLM Royal Dutch",
  IBE: "Iberia",
  VLG: "Vueling",
  SAS: "SAS Scandinavian",
  FIN: "Finnair",
  AUA: "Austrian Airlines",
  SWR: "Swiss Int'l Air Lines",
  TAP: "TAP Air Portugal",
  AZA: "ITA Airways",
  EWG: "Eurowings",
  WZZ: "Wizz Air",
  NAX: "Norwegian Air",
  BEL: "Brussels Airlines",
  LOT: "LOT Polish Airlines",
  AEE: "Aegean Airlines",
  THY: "Turkish Airlines",
  ROT: "TAROM",
  CSA: "Czech Airlines",
  ICE: "Icelandair",
  EIN: "Aer Lingus",
  TRA: "Transavia",
  BER: "Air Berlin",
  CFE: "CityJet",
  SXS: "SunExpress",
  PGT: "Pegasus Airlines",
  TVF: "Transavia France",

  // Middle East
  UAE: "Emirates",
  QTR: "Qatar Airways",
  ETD: "Etihad Airways",
  SVA: "Saudia",
  GFA: "Gulf Air",
  OMA: "Oman Air",
  RJA: "Royal Jordanian",
  MEA: "Middle East Airlines",
  KAC: "Kuwait Airways",
  FDB: "flydubai",
  AXB: "Air India Express",
  IAW: "Iraqi Airways",

  // Asia Pacific
  CPA: "Cathay Pacific",
  SIA: "Singapore Airlines",
  ANA: "All Nippon Airways",
  JAL: "Japan Airlines",
  KAL: "Korean Air",
  AAR: "Asiana Airlines",
  THA: "Thai Airways",
  MAS: "Malaysia Airlines",
  GIA: "Garuda Indonesia",
  CES: "China Eastern",
  CSN: "China Southern",
  CCA: "Air China",
  HDA: "China Express Air",
  AIR: "Air India",
  IGO: "IndiGo",
  SEJ: "SpiceJet",
  AKX: "ANA Wings",
  EVA: "EVA Air",
  CAL: "China Airlines",
  VJC: "VietJet Air",
  HVN: "Vietnam Airlines",
  CEB: "Cebu Pacific",
  PAL: "Philippine Airlines",
  APJ: "Peach Aviation",
  JST: "Jetstar Airways",
  AXM: "AirAsia",
  QFA: "Qantas",
  ANZ: "Air New Zealand",
  VOZ: "Virgin Australia",
  MXD: "Malindo Air",
  SLK: "Silk Air",
  BTV: "Batik Air",

  // Africa
  SAA: "South African Airways",
  ETH: "Ethiopian Airlines",
  KQA: "Kenya Airways",
  RAM: "Royal Air Maroc",
  MSR: "EgyptAir",
  NIG: "Arik Air",
  AWT: "Air Mauritius",

  // South America
  LAN: "LATAM Airlines",
  TAM: "LATAM Brasil",
  GLO: "GOL Linhas Aereas",
  AZU: "Azul Brazilian",
  AVA: "Avianca",
  ARG: "Aerolineas Argentinas",
  CMP: "Copa Airlines",

  // Cargo
  FDX: "FedEx Express",
  UPS: "UPS Airlines",
  GTI: "Atlas Air",
  CLX: "Cargolux",
  ABW: "AirBridgeCargo",
  BOX: "Aerologic",
  MPH: "Martinair Cargo",
  QCL: "Qatar Cargo",

  // Regional
  ENY: "Envoy Air",
  RPA: "Republic Airways",
  SKW: "SkyWest Airlines",
  PDT: "Piedmont Airlines",
  JIA: "PSA Airlines",
  CPZ: "Compass Airlines",
  EDV: "Endeavor Air",
  ASH: "Mesa Airlines",
  TRS: "TriStar Air",
  BEE: "Flybe",
  CLC: "CommutAir",
  LOG: "Loganair",
};

export function getAirlineName(callsign: string | null): string | null {
  if (!callsign) return null;
  const prefix = callsign.trim().substring(0, 3).toUpperCase();
  return AIRLINES[prefix] ?? null;
}
